#! /bin/bash
## Script for bulk handbrake conversion ##


# Initialise Variables #

# Video source directory for grabbing names
source="$(ls /home/jamie/500gb/handbrake_conversions/todo/)" # enter source directory after ls

# Extra input for joining location and name strings
input="/home/jamie/500gb/handbrake_conversions/todo"

# Video output directory
out="/home/jamie/500gb/handbrake_conversions/complete"

# Video Codec: x264 | x264_10bit | nvenc_h264 | x265 | x265_10bit | x265_12bit | nvenc_h265 | mpeg4 | mpeg2 | VP8 | VP9 | theora
video="x265_10bit"

# Audio Codec: none | av_aac | copy:aac | ac3 | copy:ac3 | eac3 | copy:eac3 | copy:truehd | copy:dts | copy:dtshd | copy:mp2 | mp3 | copy:mp3 | vorbis | flac16 | flac24 | copy:flac | opus | copy
audio="flac16"

# Subtitle
sub="--all-subtitles"

# Container: av_mp4 | av_mkv | av_webm
container="av_mp4"

#### Start Script ####

# Handbrake CLI #
for i in $source

do

HandBrakeCLI -i $input/$i -o $out/$i -e $video -f $container -q 20.0 -m –all-audio -E $audio $sub  && sleep 1m

done
